name: Escribiendo para aprender.
description: >
    He decidido aprender “Machine learning” .Para un mejor aprendizaje he decidido ir escribiendo lo aprendido y 
    seleccionar un proyecto por supuesto relacionado con ML (un poco de paciencia para saber de qué se trata….) y 
    así practicar lo aprendido . Los temas a tratar serán : Estadística descriptiva, probabilidades , estadistica inferencial  
    y álgebra lineal, en cuanto a herramientas de machine learning se usará : redes neuronales, Máquinas vectores de soporte,
    K-Means, otros . Para la parte de visualización y contar historias usaremos D3.js. Y el lenguaje de programación a usar será Python.
about: >
    Soy Yuri Alberto Bermudez nacido en Nuqui-Choco. Desarrollador full stack y estudiante de matematica de
    la Universidad Nacional Sede Medellin. Si tienes algo que contarme, puedes escribirme a bermudezyuriaba[arroba].gmail.com

url: "https://yurialberto.github.io"
baseurl: "/white-paper"
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate,  jekyll-gist]

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           yurialberto
  avatar:         ""
  email:          "bermudezyuriaba@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
